### ISSUE TITLE
Mobile - Exibir primeiro o preço do varejo

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#108]
É possível exibir primeiro os preço do varejo e depois atacado no celular?

![whatsapp image 2018-06-27 at 13 28 31 1](https://user-images.githubusercontent.com/20990100/41987122-aac8066e-7a0e-11e8-9dc6-42d0d0eb599d.jpeg)

**Comment by claudineicaetano** [comment]
Nossa preferencia é que o possível comprador compre no varejo ou no atacado? Sugeri colocar o atacado primeiro por ser mais atrativo.
