### ISSUE TITLE
Mobile - O carrinho esvazia depois do cadastro

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#109]
Os produtos do carrinho são pagados depois que o usuário faz o cadastro.

![whatsapp image 2018-06-27 at 13 28 31 3](https://user-images.githubusercontent.com/20990100/41987193-d2b70922-7a0e-11e8-9398-523407a92d15.jpeg)

**Comment by claudineicaetano** [comment]
O carrinho é guardado no backend para termos estatísticas, se ele se conecta com outro usuário, ou um usuário novo, o carrinho dele está limpo.

**Comment by lucasretondo** [comment]
Mas este comportamento é ruim, concorda?

Cria uma barreia logo de cara.

**Comment by claudineicaetano** [comment]
Concordo que é ruim mesmo. Precisamos decidir se queremos saber as estatística dos usuários quando eles colocam produtos no carrinho ou se deixamos o usuário colocar o produto sem autenticar e não teremos estatística desses anônimos.

**Comment by lucasretondo** [comment]
Temos como medir o número de visitas as página carrinho.

Achou ruim ter uma barreira de entrada para gerar estatísticas.
