### ISSUE TITLE
Página inicial - Trocar as figuras dos produtos dos banners

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#122]
Trocar as 5 figuras dos produtos dos banners pelas figuras anexas:

![image](https://user-images.githubusercontent.com/20990100/42069720-9fca7c80-7b29-11e8-8651-2367b86338e7.png)

![slide5](https://user-images.githubusercontent.com/20990100/42069706-929e5ae0-7b29-11e8-815b-fad686b235d5.PNG)
![slide9](https://user-images.githubusercontent.com/20990100/42069707-92c895e4-7b29-11e8-9b46-d03a6f0d5e86.PNG)
![slide25](https://user-images.githubusercontent.com/20990100/42069708-92eeac8e-7b29-11e8-933b-82f7bf8aa84f.PNG)
![slide37](https://user-images.githubusercontent.com/20990100/42069709-930f6ca8-7b29-11e8-9ca9-81ff01d1ffa8.PNG)
![slide70](https://user-images.githubusercontent.com/20990100/42069710-932fb828-7b29-11e8-8344-61d86e23cd90.PNG)

**Comment by claudineicaetano** [comment]
Como conversamos, os banners com fundo branco ficaram ruins. Você ficou de verificar com a agência para nos enviar o fundo (aquele laranja que estava sendo usado) e as imagens dos produtos com fundo transparente.

**Comment by lucasretondo** [comment]
Eles ficaram de nos enviar as imagens esta semana. Amanhã vou falar com eles para determinar uma data. Obrigado ---- On Mon, 02 Jul 2018 18:24:33 -0300 claudineicaetano <notifications@github.com> wrote ---- Como conversamos, os banners com fundo branco ficaram ruins. Você ficou de verificar com a agência para nos enviar o fundo (aquele laranja que estava sendo usado) e as imagens dos produtos com fundo transparente. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
