### ISSUE TITLE
Sistema travou depois que exclui loja

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#145]
![image](https://user-images.githubusercontent.com/20990100/42296603-42816af8-7fce-11e8-952a-9a6112d228d5.png)

**Comment by claudineicaetano** [comment]
essas duas lojas foram inseridas direto na base lembra? Excluir elas vai ter problema mesmo. As novas funcionalidade do catalogo são vinculadas aos lojistas e excluir um lojista não exclui de fato da base, mas exclui os dados e vira uma bagunça.
