### ISSUE TITLE
ADM- Possibilitar abrir nova guia, janela

### ISSUE THREAD

**Issue by JuliaAlmeida** [claudineicaetano/backlog-pcs#160]
Teria como no painel administrativo poder abrir nova guia?
Para facilitar nas edições de produtos, categorias e subcategorias.

**Comment by claudineicaetano** [comment]
Foi feito um ajuste para abrir em nova aba, mas para não precisar colocar sempre a senha deve ser marcado a opção "Lembrar-se de mim" no login.
