### ISSUE TITLE
Pedido - Permite pedidos de qualquer lugar

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#191]
O sistema permite a criação de pedidos de qualquer lugar.

Pedido loja sorocaba
![image](https://user-images.githubusercontent.com/20990100/47193704-c3b05300-d32a-11e8-9e8f-c2667cd911b2.png)

obra minas gerais
![image](https://user-images.githubusercontent.com/20990100/47193716-d0cd4200-d32a-11e8-9917-02c720f10bad.png)

**Comment by claudineicaetano** [comment]
Isso está assim de propósito já que agora pode se colocar um preço alto para distancias maior que um certa distância. Tiramos a trava para que possa ser indexado no google shopping.

**Comment by lucasretondo** [comment]
Temos que pensar nisso com mais calma, apesar da loja puder cobrar o frete para distância grandes, não faz sentido ignorar o raio de entrega pois pode ocorrer pedidos fora da região dela.

Enfim, temos que avaliar os impactos positivos e negativos com mais calma.
