### ISSUE TITLE
Oferta de Produtos - Precisamos mudar a descrição dos blocos cerâmicos

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#32]
Precisamos incluir a resistência nas descrições dos blocos cerâmicos.
![image](https://user-images.githubusercontent.com/20990100/38223902-d062f0c0-36c3-11e8-85fd-41e315738c8f.png)

A novas descrições são:
Bloco   cerâmico estrutural 9x19x19cm 6,0 MPa (peça)
Bloco cerâmico estrutural   9x19x39cm 6,0 MPa (carga 2.500 peças)
Bloco cerâmico estrutural   14x19x14cm 6,0 MPa (peça)
Bloco cerâmico estrutural   14x19x19cm 6,0 MPa (peça)
Bloco cerâmico estrutural   14x19x29cm 6,0 MPa (carga 2.700 peças)
Bloco cerâmico estrutural   14x19x39cm 6,0 MPa (carga 2.200 peças)
Bloco cerâmico estrutural   14x19x44cm 6,0 MPa (peça)
Bloco cerâmico estrutural   19x19x19cm 6,0 MPa (peça)
Bloco cerâmico estrutural   19x19x39cm 6,0 MPa (carga 1.800 peças)

**Comment by claudineicaetano** [comment]
Os títulos/descrição precisam estar entre 40 e 60 caracteres. O ideal são 50, senão quebra no layout previsto.

**Comment by lucasretondo** [comment]
Tentei fazer isso, mas não consegue para todos os casos.



Tem algum que esta muito ruim?












---- On Qua, 04 abr 2018 15:47:19 -0300 claudineicaetano &lt;notifications@github.com&gt; wrote ----




Os títulos/descrição precisam estar entre 40 e 60 caracteres. O ideal são 50, senão quebra no layout previsto.
