### ISSUE TITLE
E-mails de notificação - Alterar os textos dos e-mails de notificação

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#33]
Alterar os textos dos e-mails de notificação conforme o doc anexo.
[E-mails v3.docx](https://github.com/claudineicaetano/backlog-pcs/files/1869890/E-mails.v3.docx)

**Comment by lucasretondo** [comment]
Não esta aparecendo o número do pedido no e-mail de mensagem recebida:
![image](https://user-images.githubusercontent.com/20990100/38450083-648a0978-39ee-11e8-9037-b40246135cf9.png)

**Comment by claudineicaetano** [comment]
Corrigido no backend.
