### ISSUE TITLE
Oferta de Produtos - Inserir 23 novos produtos

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#35]
Precisamos inserir 23 novos produtos na categoria "Aço". Para isso estou anexando nesta issue:
- INSERT de Materiais e Preços
- Imagens do produtos: https://1drv.ms/u/s!Ao7UUz0P8SUSlGdz2CVnYP3MrNGV
- Planilha com o DE PARA do material vs. imagem

[SQL INSERT NOVOS MATERIAIS 20180403 v1.txt](https://github.com/claudineicaetano/backlog-pcs/files/1872123/SQL.INSERT.NOVOS.MATERIAIS.20180403.v1.txt)
[SQL INSERT PREÇOS 20180403 v1.txt](https://github.com/claudineicaetano/backlog-pcs/files/1872125/SQL.INSERT.PRECOS.20180403.v1.txt)
[DE PARA Material vs Imagem.xlsx](https://github.com/claudineicaetano/backlog-pcs/files/1872135/DE.PARA.Material.vs.Imagem.xlsx)

**Comment by claudineicaetano** [comment]
SQL INSERT PREÇOS 20180403 v1.txt
![screen shot 2018-04-04 at 15 28 19](https://user-images.githubusercontent.com/22913165/38327407-887a78e4-381e-11e8-8fa6-d0e698bccd75.png)

**Comment by lucasretondo** [comment]
Estranho, no txt o "ç" esta certo:





De qualquer forma vi que no arquivo temos "/" e isso esta errado.



Então estou te mandando a v2 com isso corrigido.



Obrigado









---- On Qua, 04 abr 2018 15:40:47 -0300 claudineicaetano &lt;notifications@github.com&gt; wrote ----




SQL INSERT PREÇOS 20180403 v1.txt 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.









INSERT INTO shopkeeper_fixed_prices (id, opt_lock, brand0, brand1, out_of_scope, price0, price1, selected, unavailable, fp_product, fp_shopkeeper, fp_unit ) VALUES
(940, 1, 'A�o_cortado_e_dobrado_CA-60_4,2mm_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120115, 253, 20033),
(941, 1, 'A�o_cortado_e_dobrado_CA-60_5mm_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120116, 253, 20033),
(942, 1, 'A�o_cortado_e_dobrado_CA-50_6,3mm_ou_14''_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120117, 253, 20033),
(943, 1, 'A�o_cortado_e_dobrado_CA-50_8mm_ou_516''_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120118, 253, 20033),
(944, 1, 'A�o_cortado_e_dobrado_CA-50_10mm_ou_38''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120119, 253, 20033),
(945, 1, 'A�o_cortado_e_dobrado_CA-50_12,5mm_ou_12''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120120, 253, 20033),
(946, 1, 'A�o_cortado_e_dobrado_CA-50_16mm_ou_58''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120121, 253, 20033),
(947, 1, 'Barra_de_a�o_CA-50_16mm_ou_58''_(12_metros).JPG', 15, FALSE,86.60, NULL, TRUE, FALSE, 120128, 253, 20003),
(948, 1, 'Barra_de_a�o_CA-60_4,2mm_(12_metros).JPG', 15, FALSE,6.70, NULL, TRUE, FALSE, 120122, 253, 20003),
(949, 1, 'Barra_de_a�o_CA-60_5mm_(12_metros).JPG', 15, FALSE,9.15, NULL, TRUE, FALSE, 120123, 253, 20003),
(950, 1, 'Coluna_de_a�o_8mm_7x14cm_(pe�a_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120129, 253, 20026),
(951, 1, 'Coluna_de_a�o_8mm_7x17cm_(pe�a_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120130, 253, 20026),
(952, 1, 'Coluna_de_a�o_8mm_7x20cm_(pe�a_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120131, 253, 20026),
(953, 1, 'Coluna_de_a�o_10mm_7x14cm_(pe�a_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120132, 253, 20026),
(954, 1, 'Coluna_de_a�o_10mm_7x17cm_(pe�a_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120133, 253, 20026),
(955, 1, 'Coluna_de_a�o_10mm_7x20cm_(pe�a_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120134, 253, 20026),
(956, 1, 'Tela_ou_malha_de_a�o_3,4mm_leve,_20x20cm,_2x3_metros_(pe�a).JPG', 15, FALSE,25.00, NULL, TRUE, FALSE, 120135, 253, 20026),
(957, 1, 'Tela_ou_malha_de_a�o_3,4mm_m�dia,_15x15cm,_2x3_metros_(pe�a).JPG', 15, FALSE,35.00, NULL, TRUE, FALSE, 120136, 253, 20026),
(958, 1, 'Tela_ou_malha_de_a�o_4,2mm_refor�ada,_15x15cm,_2x3_metros_(pe�a).JPG', 15, FALSE,50.00, NULL, TRUE, FALSE, 120137, 253, 20026),
(959, 1, 'Tela_ou_malha_de_a�o_4,2mm_pesada,_10x10cm,_2x3_metros_(pe�a).JPG', 15, FALSE,75.00, NULL, TRUE, FALSE, 120138, 253, 20026),
(960, 1, 'Treli�a_de_a�o_H8_(12cm)_-_leve_-_6x3,4x4,2mm_(pe�a_6_metros).JPG', 15, FALSE,22.00, NULL, TRUE, FALSE, 120139, 253, 20034),
(961, 1, 'Treli�a_de_a�o_H8_(12cm)_-_pesada_-_6x4,2x4,2mm_(pe�a_6_metros).JPG', 15, FALSE,24.70, NULL, TRUE, FALSE, 120140, 253, 20034),
(962, 1, 'Treli�a_de_a�o_H12_(16cm)_-_pesada_-_6x4,2x5mm_(pe�a_6_metros).JPG', 15, FALSE,31.50, NULL, TRUE, FALSE, 120141, 253, 20034)

**Comment by claudineicaetano** [comment]
Acho que o problema é que não está na extinção do arquivo ser txt e sim no tipo de codificação. O ideal é que seja UTF-8. https://pt.wikipedia.org/wiki/UTF-8

**Comment by lucasretondo** [comment]
Agora vc falou grego...



O que eu faço?









---- On Wed, 04 Apr 2018 15:49:44 -0300 claudineicaetano &lt;notifications@github.com&gt; wrote ----




Acho que o problema é que não está na extinção do arquivo ser txt e sim no tipo de codificação. O ideal é que seja UTF-8. https://pt.wikipedia.org/wiki/UTF-8

**Comment by claudineicaetano** [comment]
Se você não conseguir gerar com a codificação correta. Me envie colocado no corpo do email. Como é uma lista pequena de coisa dá para colar até aqui no corpo dessa mensagem.

**Comment by lucasretondo** [comment]
Segue:



INSERT INTO shopkeeper_fixed_prices (id, opt_lock, brand0, brand1, out_of_scope, price0, price1, selected, unavailable, fp_product, fp_shopkeeper, fp_unit ) VALUES 

(940, 1, 'Aço_cortado_e_dobrado_CA-60_4,2mm_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120115, 253, 20033),

(941, 1, 'Aço_cortado_e_dobrado_CA-60_5mm_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120116, 253, 20033),

(942, 1, 'Aço_cortado_e_dobrado_CA-50_6,3mm_ou_14''_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120117, 253, 20033),

(943, 1, 'Aço_cortado_e_dobrado_CA-50_8mm_ou_516''_(kg).JPG', 15, FALSE,6.79, NULL, TRUE, FALSE, 120118, 253, 20033),

(944, 1, 'Aço_cortado_e_dobrado_CA-50_10mm_ou_38''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120119, 253, 20033),

(945, 1, 'Aço_cortado_e_dobrado_CA-50_12,5mm_ou_12''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120120, 253, 20033),

(946, 1, 'Aço_cortado_e_dobrado_CA-50_16mm_ou_58''_(kg).JPG', 15, FALSE,5.37, NULL, TRUE, FALSE, 120121, 253, 20033),

(947, 1, 'Barra_de_aço_CA-50_16mm_ou_58''_(12_metros).JPG', 15, FALSE,86.60, NULL, TRUE, FALSE, 120128, 253, 20003),

(948, 1, 'Barra_de_aço_CA-60_4,2mm_(12_metros).JPG', 15, FALSE,6.70, NULL, TRUE, FALSE, 120122, 253, 20003),

(949, 1, 'Barra_de_aço_CA-60_5mm_(12_metros).JPG', 15, FALSE,9.15, NULL, TRUE, FALSE, 120123, 253, 20003),

(950, 1, 'Coluna_de_aço_8mm_7x14cm_(peça_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120129, 253, 20026),

(951, 1, 'Coluna_de_aço_8mm_7x17cm_(peça_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120130, 253, 20026),

(952, 1, 'Coluna_de_aço_8mm_7x20cm_(peça_6_metros).JPG', 15, FALSE,81.47, NULL, TRUE, FALSE, 120131, 253, 20026),

(953, 1, 'Coluna_de_aço_10mm_7x14cm_(peça_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120132, 253, 20026),

(954, 1, 'Coluna_de_aço_10mm_7x17cm_(peça_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120133, 253, 20026),

(955, 1, 'Coluna_de_aço_10mm_7x20cm_(peça_6_metros).JPG', 15, FALSE,96.63, NULL, TRUE, FALSE, 120134, 253, 20026),

(956, 1, 'Tela_ou_malha_de_aço_3,4mm_leve,_20x20cm,_2x3_metros_(peça).JPG', 15, FALSE,25.00, NULL, TRUE, FALSE, 120135, 253, 20026),

(957, 1, 'Tela_ou_malha_de_aço_3,4mm_média,_15x15cm,_2x3_metros_(peça).JPG', 15, FALSE,35.00, NULL, TRUE, FALSE, 120136, 253, 20026),

(958, 1, 'Tela_ou_malha_de_aço_4,2mm_reforçada,_15x15cm,_2x3_metros_(peça).JPG', 15, FALSE,50.00, NULL, TRUE, FALSE, 120137, 253, 20026),

(959, 1, 'Tela_ou_malha_de_aço_4,2mm_pesada,_10x10cm,_2x3_metros_(peça).JPG', 15, FALSE,75.00, NULL, TRUE, FALSE, 120138, 253, 20026),

(960, 1, 'Treliça_de_aço_H8_(12cm)_-_leve_-_6x3,4x4,2mm_(peça_6_metros).JPG', 15, FALSE,22.00, NULL, TRUE, FALSE, 120139, 253, 20034),

(961, 1, 'Treliça_de_aço_H8_(12cm)_-_pesada_-_6x4,2x4,2mm_(peça_6_metros).JPG', 15, FALSE,24.70, NULL, TRUE, FALSE, 120140, 253, 20034),

(962, 1, 'Treliça_de_aço_H12_(16cm)_-_pesada_-_6x4,2x5mm_(peça_6_metros).JPG', 15, FALSE,31.50, NULL, TRUE, FALSE, 120141, 253, 20034)














---- On Qua, 04 abr 2018 16:35:02 -0300 claudineicaetano &lt;notifications@github.com&gt; wrote ----




Se você não conseguir gerar com a codificação correta. Me envie colocado no corpo do email. Como é uma lista pequena de coisa dá para colar até aqui no corpo dessa mensagem.
