### ISSUE TITLE
Ajuda - Não abre o termo de uso

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#67]
Ao clicar nos links do termo de uso abre a página inicial e não o página do termo de uso.
![image](https://user-images.githubusercontent.com/20990100/40368382-0c16f980-5db2-11e8-9ac4-189911e332b2.png)

**Comment by claudineicaetano** [comment]
Acabei de verificar onde está o problema. No json os links estão errados. Por exemplo https://pdcc.angularlabs.com.br/consumidor/painel/cadastro/ deveria ser https://pdcc.angularlabs.com.br/consumidor/painel/cadastro veja que está sem a "/" no final. Vou pedir para corrigir aqui, mas sua versão aí vai ficar desatualizada. Portanto corrija daí também.

**Comment by lucasretondo** [comment]
Blz, sabia que era algo do tipo. Obrigado ---- On Ter, 03 jul 2018 08:41:26 -0300 claudineicaetano <notifications@github.com> wrote ---- Acabei de verificar onde está o problema. No json os links estão errados. Por exemplo https://pdcc.angularlabs.com.br/consumidor/painel/cadastro/ deveria ser https://pdcc.angularlabs.com.br/consumidor/painel/cadastro veja que está sem a "/" no final. Vou pedir para corrigir aqui, mas sua versão aí vai ficar desatualizada. Portanto corrija daí também. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
