### ISSUE TITLE
Carrinho - Final de cartão 1 ou 4 

### ISSUE THREAD

**Issue by JuliaAlmeida** [claudineicaetano/backlog-pcs#78]
Logo após limpar o cachê no carrinho se utilizo o final do cartão 1 ou 4 abre uma nova guia com a sequinte imagem:
![image](https://user-images.githubusercontent.com/30830371/40618720-c89250ea-6268-11e8-84aa-cf3c9ae46087.png)
Se eu já fiz algum pedido e realizo outro utilizando o final 4 ou 1 não abre essa nova guia.

**Comment by claudineicaetano** [comment]
O manual do sandbox, permite que apenas os finais 1 sejam aceitos. Segue alista de erros.
![screen shot 2018-06-06 at 16 48 08](https://user-images.githubusercontent.com/22913165/41061747-07ea6320-69aa-11e8-9998-5e677c1635b7.png)
