### ISSUE TITLE
Pedido - Melhorar as mensagens de erro do cartão

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#82]
Melhorar as mensagens de erro do cartão: 

![image](https://user-images.githubusercontent.com/20990100/40623211-09835b68-627c-11e8-8bb2-6e75cda27518.png)

DE “Não autorizada” PARA “O pagamento não foi autorizado. Entre em contato com a operadora do cartão para mais informações.”

DE “Cartão expirado” PARA “Este cartão está expirado. Entre em contato com a operadora do cartão para mais informações.”

DE “Cartão bloqueado” PARA “Este cartão está bloqueado. Entre em contato com a operadora do cartão para mais informações.”

DE “Time Out” PARA “Ocorreu um erro inesperado. Tente novamente mais tarde.”

DE “Cartão cancelado” PARA “Este cartão está cancelado. Entre em contato com a operadora do cartão para mais informações.”

DE “Cartão com problemas” PARA “O operadora não autorizou o pagamento. Entre em contato com a operadora do cartão para mais informações.”

**Comment by lucasretondo** [comment]
As mensagens estão cortando:
![image](https://user-images.githubusercontent.com/20990100/41114669-77dde25e-6a5b-11e8-96ee-2d42b08d29ae.png)

É mais fácil adicionar uma linha ou mudar a mensagem?

**Comment by claudineicaetano** [comment]
returnCodeMessages = new HashMap<>();
    returnCodeMessages.put("05",
            "O pagamento não foi autorizado. Entre em contato com a operadora do cartão para mais informações.");
    returnCodeMessages.put("57",
            "Este cartão está expirado. Entre em contato com a operadora do cartão para mais informações.");
    returnCodeMessages.put("78",
            "Este cartão está bloqueado. Entre em contato com a operadora do cartão para mais informações");
    returnCodeMessages.put("99",
            "Ocorreu um erro inesperado. Tente novamente mais tarde.");
    returnCodeMessages.put("77",
            "Este cartão está cancelado. Entre em contato com a operadora do cartão para mais informações.");
    returnCodeMessages.put("70",
            "O operadora não autorizou o pagamento. Entre em contato com a operadora do cartão para mais informações.");
  }
