### ISSUE TITLE
Informações - Não aceita funções de Json

### ISSUE THREAD

**Issue by lucasretondo** [claudineicaetano/backlog-pcs#99]
Não permite colocar links e usar funções de Json nos campos de informações de produtos e categorias:

![image](https://user-images.githubusercontent.com/20990100/41981725-ff01c8f0-79ff-11e8-9366-35b29ef7b9ef.png)
 
![image](https://user-images.githubusercontent.com/20990100/41981752-0c5324d6-7a00-11e8-9659-496b87889a90.png)

**Comment by claudineicaetano** [comment]
Foi inserido um editor de texto para permitir inserções de link como no Wordpress.
